FROM bitnamisecure/nginx:latest@sha256:9c59d5e12c6fed2019658c07bfcea89d63647f62902222d58fe42dcb08081a15

COPY index.html /opt/bitnami/nginx/html
COPY conf/maintenance_page.conf /opt/bitnami/nginx/conf/server_blocks/