FROM bitnamisecure/nginx:latest@sha256:b8d42f076789079bd84f114df5ad880be5d99cb9266b010841a7da0e64c1ffee

COPY index.html /opt/bitnami/nginx/html
COPY conf/maintenance_page.conf /opt/bitnami/nginx/conf/server_blocks/